dist: xenial
language: python
python:
- '3.7'
install:
- make
services:
- postgresql
- mysql
script:
- make test
after_success:
- coveralls
before_script:
- mkdir $HOME/.process_tracker
- mv configs/${DB}_config.ini $HOME/.process_tracker/process_tracker_config.ini
- if [[ "$DB" == "postgres" ]]; then psql -f dbscripts/postgresql_account_create.sql -U postgres; fi
- if [[ "$DB" == "postgres" ]]; then psql -f dbscripts/postgresql_process_tracker.sql process_tracking -U postgres; fi
- if [[ "$DB" == "postgres" ]]; then psql -f dbscripts/postgresqlpostgresql_process_tracker_defaults.sql_process_tracker_defaults.sql process_tracking -U postgres; fi
- if [[ "$DB" == "mysql" ]]; then mysql -u root < dbscripts/mysql_account_create.sql; fi
- if [[ "$DB" == "mysql" ]]; then mysql -u root < dbscripts/mysql_process_tracker.sql; fi
- if [[ "$DB" == "mysql" ]]; then mysql -u root < dbscripts/mysql_process_tracker_defaults.sql; fi
env:
- DB=postgres
- DB=mysql
deploy:
  - provider: releases
    api_key:
      secure: T02NqddtE6qN/2ugvx/anZFzqmfnpWy2uCWcW4jg+pgiNI8GhRr0zh5Fwfe3aGnzAZLEgEMSgNWsM5CpniSbquioijqOEL/9xo8gZn6wV9VEjToR1/FEvGZm08T/Grc4rEYzjNgZu8eLUtC6Mg5l1nm6tGNEBE1oAKvflL77pnSGPL9enhmQupzbSQxNJ7rOuR7OgxuaFygP0Tne56Ca1LU6rAHmzqKJh6hI6eZARSikjLvgEHThcvZPc3gPfYMAc7i+dTx17Q3zQQGaHvySuLp+5aR3a+3xaFQPCmecLeiuX2yCiVVs9BOcrTeJOHivRYv6Cj9i60NUblvBlwOfJdo6uiArYTbVP/Aj8d1+8ruM5RdSeEyzlZlKarRN24CvH99OxU+LZGF5JgKV9UrTlytWl6ENOJcZq91LjejzkxGtKFp67abh8WPqqSGdcwA5VeI+QcHWDvc/3T/CdvljH4ivZRKeTCArAe4ce94WRvnJ6W0o3PoxrYxprhDFUyGUmrRJaLy/22qkkaifBQ9ljFgWNqeJtSGej87QhUVlfVnSS/6intr/sgd/vT0sDOU8RMTDxji3vkKKO1hfzBPKousqq48ddWGUxzAGwRoGULVbpwf8IIYApxlqotp40GpNOPJR6WrMUhHu/7jWGmvy66HPi4rQXKlaIWJLaH1f1yo=
    on:
      repo: OpenDataAlex/process_tracker_python
      tags: true
    skip_cleanup: true
  - provider: pypi
    user: opendataalex
    distributions: "sdist bdist_wheel"
    password:
      secure: jYe8ygGYuJox5f1vQvraIDNlR2Yk/+/afIXdsxaxRi/QN135rIHxRih24iYv8ZQewfW+w4CveEPz2pr0ew5NG8hm2MD5hQZI/A2QE4BC53Tr3xMAWSdPQgcI1rX4Ieu6BHTS3jet212yLuBk41GdASKztz+s/CVvVqT0A29U1b85OVzoVHz6OTgaM1m0pKeJE6Ho66r5O6J7ClZfEY4RJ8jROmrT7ufW3hEs/VQXwfAUWcjy6l5H5VYTLa/g94MgQ+0WmgcdUbB8s3c2q7n4RiaVEowZOLtBmRElDIPiLJC8JGAIFKcf5W8pzXK/ZhZhY3ppgmBvRVeyPdiAwjysionzl4vIlNxC28acI3HzvJbAdvwPsuMD+pnTo/LKRqqvGey2NSnMPmzGXxzqVUqQ5Wa1Yzdcqg8mbWHFRw9icMWKM84CnDBvqkmJcfnj5R4X6Rc77mr9jc5LMMBBblNtY7dQc2AooframujGA2mP1xABQ9vOSg89MdnlhHrgEK6m+Pz0S2hhlsGRw9yMF9L4Q1ie7xKeE49L3HKZSjKEgSMv9y9RbqnmW32F0UoKgWkCJE8DV9wbZe5Htn+lpwmXI0vu+cxnqsiZvG8wjm+klJGn5F84OFTN3zQOC/kIBXQXvutZYtgF0vofdCmKQzK9istl16Eur1r4NCbov3oM97o=
    on:
      tags: true
    skip_cleanup: true