name: process-tracker-python
on:
  push:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo code
        uses: actions/checkout@v2
        
      - name: create app directory
        run: mkdir ${GITHUB_WORKSPACE}/.process_tracker

      - name: place config file
        run: cp ${GITHUB_WORKSPACE}/configs/process_tracker_config_dev.ini ${GITHUB_WORKSPACE}/.process_tracker/process_tracker_config_dev.ini

      - name: install python
        uses: gabrielfalcao/pyenv-action@v7
        with:
          default: 3.8.6
          command: pip install -U pip
          
      - name: install pipenv
        run: pip install pipenv
      
      - name: install cython (dependency)
        run: pip install cython

      - name: install requirements
        run: pipenv install --dev

  postgresql-test:
    needs: setup
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432

    steps:
      - name: run postgresql account creation
        run: psql -f ${GITHUB_WORKSPACE}/dbscripts/postgresql_account_create.sql -U postgres -h localhost
      - name: run postgresql database creation
        run: psql -f ${GITHUB_WORKSPACE}/dbscripts/postgresql_process_tracker.sql process_tracker -U postgres -h localhost
      - name: run postgresql database defaults creation
        run: psql -f ${GITHUB_WORKSPACE}/dbscripts/postgresql_process_tracker_defaults.sql process_tracker -U postgres -h localhost

      - name: run test suite
        run: make test

      - name: Coveralls Results
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          github-token: ${{ secrets.github_token }}
          flag-name: Unit Test


  mysql-test:
    needs: setup
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql

    steps:
       - name: run mysql account creation
         run: mysql -u root < ${GITHUB_WORKSPACE}/dbscripts/mysql_account_create.sql
       - name: run mysql database creation
         run: mysql -u root < ${GITHUB_WORKSPACE}/dbscripts/mysql_process_tracker.sql
       - name: run mysql database defaults creation
         run: mysql -u root < ${GITHUB_WORKSPACE}/dbscripts/mysql_process_tracker_defaults.sql

       - name: run test suite
         run: make test

       - name: Coveralls Results
         uses: AndreMiras/coveralls-python-action@develop
         with:
           parallel: true
           github-token: ${{ secrets.github_token }}
           flag-name: Unit Test


  finish:
    needs: [mysql-test, postgresql-test]
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true

